# Generated by Django 4.0.3 on 2022-06-14 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_ispublished_alter_movie_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('A', 'AKSİYON'), ('M', 'MACERA'), ('B', 'BİLİM-KURGU'), ('N', 'ANİMASYON'), ('B', 'BİYOGRAFİ')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.TextField(verbose_name='Film Afişi'),
        ),
    ]
