# Generated by Django 4.0.3 on 2022-06-14 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_category_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('EY', 'En Yeniler'), ('P', 'Popüler'), ('ÖÇ', 'Öne Çıkan')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('A', 'AKSİYON'), ('M', 'MACERA'), ('B', 'BİLİM-KURGU'), ('A', 'ANİMASYON'), ('B', 'BİYOGRAFİ')], max_length=1),
        ),
    ]
